[package]
name = "day09"
version = "0.1.0"
edition = "2021"

[dependencies]
array2d = { version = "0.3.0" }
sscanf = { version = "0.4.0" }

[[bin]]
name = "part1"
path = "src/part1.rs"

[[bin]]
name = "part2"
path = "src/part2.rs"